[project]
name = "roberta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.6.0",
    "matplotlib>=3.10.3",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "transformers>=4.52.3",
]
